### ISSUE TITLE
Dot makes path relative and thus unable to mount the download path

### ISSUE THREAD

**Issue by wernersbacher** [LordZeuss/arr-installer#4]
See 
https://github.com/LordZeuss/arr-installer/blob/4b276ac1409b336cfe3fb8307bb8c42bb4aaa4c9/arr-installer.sh#L264
https://github.com/LordZeuss/arr-installer/blob/4b276ac1409b336cfe3fb8307bb8c42bb4aaa4c9/arr-installer.sh#L265

Just remove the two dots, then it works.

**Comment by LordZeuss** [comment]
I must've accidently added this when modifying the code. Thanks for bringing it to my attention! Fixed :)
